{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 71,
      "metadata": {
        "id": "wglztA6gXOcB"
      },
      "outputs": [],
      "source": [
        "#Michelle Brenes\n",
        "#Laser Rivera\n",
        "#Julio Marin \n",
        "#Mohnish Hemdev\n",
        "#Jayson Morán"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 72,
      "metadata": {},
      "outputs": [],
      "source": [
        "#pip install pandas\n",
        "#pip install dash\n",
        "#pip install geopandas\n",
        "#pip install pipwin\n",
        "#pip install fiona\n",
        "#pip install wheel"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 73,
      "metadata": {},
      "outputs": [],
      "source": [
        "import dash\n",
        "import dash_core_components as dcc \n",
        "import dash_html_components as html\n",
        "import plotly.express as px\n",
        "import pandas as pd\n",
        "from dash.dependencies import Input,Output\n",
        "import matplotlib.pyplot as plt\n",
        "from urllib.request import urlopen\n",
        "import geopandas as gpd"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 74,
      "metadata": {},
      "outputs": [],
      "source": [
        "#Importe del json que contiene al mapa de panama\n",
        "path = 'https://raw.githubusercontent.com/JaysonAMR/Semestral_Topicos/main/Json/PAN_ADM01_PROV_V01.topo.json'\n",
        "geo_pan = gpd.read_file(path)\n",
        "\n",
        "#Importe del csv con los datos del movimiento de contenedores de los puertos\n",
        "df = pd.read_csv('https://raw.githubusercontent.com/JaysonAMR/Semestral_Topicos/main/Resumido-por-a%C3%B1os.csv')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 75,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>id</th>\n",
              "      <th>COD_PROV</th>\n",
              "      <th>PROV_NAME</th>\n",
              "      <th>ISO_CODE</th>\n",
              "      <th>geometry</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>None</td>\n",
              "      <td>01</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>PA-1</td>\n",
              "      <td>MULTIPOLYGON (((-82.00026 8.95718, -82.01260 8...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>None</td>\n",
              "      <td>04</td>\n",
              "      <td>Chiriquí</td>\n",
              "      <td>PA-4</td>\n",
              "      <td>MULTIPOLYGON (((-82.44513 7.87112, -82.44337 7...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>None</td>\n",
              "      <td>02</td>\n",
              "      <td>Coclé</td>\n",
              "      <td>PA-2</td>\n",
              "      <td>POLYGON ((-80.13616 8.96596, -80.14497 8.94522...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>None</td>\n",
              "      <td>03</td>\n",
              "      <td>Colón</td>\n",
              "      <td>PA-3</td>\n",
              "      <td>MULTIPOLYGON (((-79.85114 9.39667, -79.84644 9...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>None</td>\n",
              "      <td>05</td>\n",
              "      <td>Darién</td>\n",
              "      <td>PA-5</td>\n",
              "      <td>MULTIPOLYGON (((-78.01407 8.23574, -77.99350 8...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "     id COD_PROV       PROV_NAME ISO_CODE  \\\n",
              "0  None       01  Bocas del Toro     PA-1   \n",
              "1  None       04        Chiriquí     PA-4   \n",
              "2  None       02           Coclé     PA-2   \n",
              "3  None       03           Colón     PA-3   \n",
              "4  None       05          Darién     PA-5   \n",
              "\n",
              "                                            geometry  \n",
              "0  MULTIPOLYGON (((-82.00026 8.95718, -82.01260 8...  \n",
              "1  MULTIPOLYGON (((-82.44513 7.87112, -82.44337 7...  \n",
              "2  POLYGON ((-80.13616 8.96596, -80.14497 8.94522...  \n",
              "3  MULTIPOLYGON (((-79.85114 9.39667, -79.84644 9...  \n",
              "4  MULTIPOLYGON (((-78.01407 8.23574, -77.99350 8...  "
            ]
          },
          "execution_count": 75,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "geo_pan.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 76,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>COD_PROV</th>\n",
              "      <th>PROV_NAME</th>\n",
              "      <th>Puerto</th>\n",
              "      <th>Año</th>\n",
              "      <th>Trasbordo</th>\n",
              "      <th>Local</th>\n",
              "      <th>Zona Libre</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>Bocas Fruit Co.</td>\n",
              "      <td>2017</td>\n",
              "      <td>0</td>\n",
              "      <td>16488</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>Bocas Fruit Co.</td>\n",
              "      <td>2018</td>\n",
              "      <td>0</td>\n",
              "      <td>22896</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>1</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>Bocas Fruit Co.</td>\n",
              "      <td>2019</td>\n",
              "      <td>0</td>\n",
              "      <td>58534</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>Bocas Fruit Co.</td>\n",
              "      <td>2020</td>\n",
              "      <td>12362</td>\n",
              "      <td>83400</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>1</td>\n",
              "      <td>Bocas del Toro</td>\n",
              "      <td>Bocas Fruit Co.</td>\n",
              "      <td>2021</td>\n",
              "      <td>53958</td>\n",
              "      <td>63834</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "   COD_PROV       PROV_NAME            Puerto   Año  Trasbordo  Local  \\\n",
              "0         1  Bocas del Toro  Bocas Fruit Co.   2017          0  16488   \n",
              "1         1  Bocas del Toro  Bocas Fruit Co.   2018          0  22896   \n",
              "2         1  Bocas del Toro  Bocas Fruit Co.   2019          0  58534   \n",
              "3         1  Bocas del Toro  Bocas Fruit Co.   2020      12362  83400   \n",
              "4         1  Bocas del Toro  Bocas Fruit Co.   2021      53958  63834   \n",
              "\n",
              "   Zona Libre  \n",
              "0           0  \n",
              "1           0  \n",
              "2           0  \n",
              "3           0  \n",
              "4           0  "
            ]
          },
          "execution_count": 76,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "df.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 77,
      "metadata": {},
      "outputs": [],
      "source": [
        "app = dash.Dash(__name__)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 78,
      "metadata": {},
      "outputs": [],
      "source": [
        "app.layout = html.Div([\n",
        "    \n",
        "    html.Div([\n",
        "        html.H1('Movimientos de contenedores en el SPN'),\n",
        "        html.Img(src='assets/contenedor.png')\n",
        "    ], className = 'banner'),\n",
        "\n",
        "    html.Div([\n",
        "        html.Div([\n",
        "            html.P('Selecciona el tipo de transito', className= 'flix_label', style={'color':'black', 'margin-top': '2px'}),\n",
        "            dcc.RadioItems( id= 'año-radioitem',\n",
        "                            labelStyle={'display': 'inline-block'},\n",
        "                            options=[\n",
        "                                {'label' : 'Local', 'value' : 'Local'},\n",
        "                                {'label' : 'Trasbordo', 'value' : 'Trasbordo'},\n",
        "                                {'label' : 'Zona Libre', 'value' : 'Zona Libre'}\n",
        "                            ], value= 'Año',\n",
        "                            style= {'text-aling' : 'center' , 'color' : 'black'}, className= 'dcc_compon'),\n",
        "        ], className= 'create_container2 five columns', style= {'margin-bottom': '20px'}),\n",
        "        \n",
        "    ], className = 'row flex-display'),\n",
        "\n",
        "    html.Div([\n",
        "        html.Div([\n",
        "            dcc.Graph(id = 'my_graph', figure = {})\n",
        "        ], className= 'create_container2 eight colums'), \n",
        "\n",
        "        html.Div([\n",
        "            dcc.Graph(id = 'mpie_graph', figure = {})\n",
        "        ], className= 'create_container2 five colums'), \n",
        "    ], className='row flex-display'),\n",
        "\n",
        "],id='mainContainer', style= {'display': 'flex', 'flex-direction': 'column'})"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 79,
      "metadata": {},
      "outputs": [],
      "source": [
        "@app.callback (\n",
        "    Output('my_graph', component_property= 'figure'),\n",
        "    [Input('año-radioitem', component_property='value')]\n",
        ")\n",
        "\n",
        "def update_graph(value):\n",
        "    if value == 'Local':\n",
        "        fig = px.bar(\n",
        "            data_frame=df(2017),\n",
        "            x = 'Puerto',\n",
        "            y = 'Local'\n",
        "            \n",
        "        )\n",
        "    elif value == 'Trasbordo':\n",
        "        fig = px.bar(\n",
        "            data_frame=df,\n",
        "            x = 'Puerto',\n",
        "            y = 'Trasbordo'\n",
        "        )\n",
        "    else:\n",
        "        fig = px.bar(\n",
        "            data_frame=df,\n",
        "            x = 'Puerto',\n",
        "            y = 'Zona Libre'\n",
        "        )\n",
        "    return fig\n",
        "\n",
        "@app.callback (\n",
        "    Output('mpie_graph', component_property= 'figure'),\n",
        "    [Input('año-radioitem', component_property='value')]\n",
        ")\n",
        "def update_graph(value):\n",
        "    if value == 'Local':\n",
        "        fig = px.choropleth(data_frame=df, \n",
        "                    geojson=geo_pan, \n",
        "                    locations='PROV_NAME', # nombre de la columna del Dataframe\n",
        "                    featureidkey='properties.PROV_NAME',  # ruta al campo del archivo GeoJSON con el que se hará la relación (nombre de los estados)\n",
        "                    color='Local', #El color depende de las cantidades\n",
        "                    color_continuous_scale=\"greens\", #greens\n",
        "                    animation_frame='Año'\n",
        "                    #scope=\"north america\"\n",
        "                   )\n",
        "        fig.update_geos(showcountries=True, showcoastlines=True, showland=True, fitbounds=\"locations\")\n",
        "    elif value == 'Trasbordo':\n",
        "        fig = px.choropleth(data_frame=df, \n",
        "                    geojson=geo_pan, \n",
        "                    locations='PROV_NAME', # nombre de la columna del Dataframe\n",
        "                    featureidkey='properties.PROV_NAME',  # ruta al campo del archivo GeoJSON con el que se hará la relación (nombre de los estados)\n",
        "                    color='Trasbordo', #El color depende de las cantidades\n",
        "                    color_continuous_scale=\"greens\", #greens\n",
        "                    animation_frame='Año'\n",
        "                    #scope=\"north america\"\n",
        "                   )\n",
        "        fig.update_geos(showcountries=True, showcoastlines=True, showland=True, fitbounds=\"locations\")\n",
        "    else:\n",
        "        fig = px.choropleth(data_frame=df, \n",
        "                    geojson=geo_pan, \n",
        "                    locations='PROV_NAME', # nombre de la columna del Dataframe\n",
        "                    featureidkey='properties.PROV_NAME',  # ruta al campo del archivo GeoJSON con el que se hará la relación (nombre de los estados)\n",
        "                    color='Zona Libre', #El color depende de las cantidades\n",
        "                    color_continuous_scale=\"greens\", #greens\n",
        "                    animation_frame='Año'\n",
        "                    #scope=\"north america\"\n",
        "                   )\n",
        "        fig.update_geos(showcountries=True, showcoastlines=True, showland=True, fitbounds=\"locations\")\n",
        "    return fig\n",
        "    "
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 80,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            " * Serving Flask app '__main__' (lazy loading)\n",
            " * Environment: production\n",
            "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
            "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
            " * Debug mode: off\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            " * Running on http://127.0.0.1:5003/ (Press CTRL+C to quit)\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET / HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /assets/s1.css?m=1627386984.0 HTTP/1.1\" 304 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /assets/stylesheet.css?m=1657734382.2705944 HTTP/1.1\" 304 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /_favicon.ico?v=2.5.1 HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /assets/contenedor.png HTTP/1.1\" 304 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:56] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:47:57] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "127.0.0.1 - - [17/Jul/2022 12:48:07] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:48:08] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:48:19] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:48:20] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:48:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:48:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "127.0.0.1 - - [17/Jul/2022 12:49:24] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:24] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:26] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:27] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:27] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:28] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n",
            "Exception on /_dash-update-component [POST]\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 2077, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1525, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1523, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\flask\\app.py\", line 1509, in dispatch_request\n",
            "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\dash.py\", line 1472, in dispatch\n",
            "    response.set_data(func(*args, outputs_list=outputs_list))\n",
            "  File \"c:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\dash\\_callback.py\", line 151, in add_context\n",
            "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
            "  File \"C:\\Users\\jayso\\AppData\\Local\\Temp\\ipykernel_36408\\3655336225.py\", line 9, in update_graph\n",
            "    data_frame=df(2017),\n",
            "TypeError: 'DataFrame' object is not callable\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "127.0.0.1 - - [17/Jul/2022 12:49:28] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:29] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [17/Jul/2022 12:49:30] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
          ]
        }
      ],
      "source": [
        "if __name__ == ('__main__'):\n",
        "    app.run_server(port=5003)\n",
        "#df = pd.read_csv(\"D:\\CATALAG\\Archivos Semestral\\PSFC.csv\")\n",
        "#df.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [
        {
          "ename": "TypeError",
          "evalue": "cannot do positional indexing on RangeIndex with these indexers [Bocas Fruit Co. Mov. De Contenedores Trasbordo] of type str",
          "output_type": "error",
          "traceback": [
            "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[1;32md:\\CATALAG\\Archivos Semestral\\Codigo\\SemestralTopicos.ipynb Celda 7\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/d%3A/CATALAG/Archivos%20Semestral/Codigo/SemestralTopicos.ipynb#ch0000007?line=0'>1</a>\u001b[0m df\u001b[39m.\u001b[39;49mhead(\u001b[39m\"\u001b[39;49m\u001b[39mBocas Fruit Co. Mov. De Contenedores Trasbordo\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\generic.py:5222\u001b[0m, in \u001b[0;36mNDFrame.head\u001b[1;34m(self, n)\u001b[0m\n\u001b[0;32m   5151\u001b[0m \u001b[39m@final\u001b[39m\n\u001b[0;32m   5152\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mhead\u001b[39m(\u001b[39mself\u001b[39m: NDFrameT, n: \u001b[39mint\u001b[39m \u001b[39m=\u001b[39m \u001b[39m5\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m NDFrameT:\n\u001b[0;32m   5153\u001b[0m     \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   5154\u001b[0m \u001b[39m    Return the first `n` rows.\u001b[39;00m\n\u001b[0;32m   5155\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   5220\u001b[0m \u001b[39m    5     parrot\u001b[39;00m\n\u001b[0;32m   5221\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> 5222\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49miloc[:n]\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\indexing.py:967\u001b[0m, in \u001b[0;36m_LocationIndexer.__getitem__\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m    964\u001b[0m axis \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39maxis \u001b[39mor\u001b[39;00m \u001b[39m0\u001b[39m\n\u001b[0;32m    966\u001b[0m maybe_callable \u001b[39m=\u001b[39m com\u001b[39m.\u001b[39mapply_if_callable(key, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mobj)\n\u001b[1;32m--> 967\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_getitem_axis(maybe_callable, axis\u001b[39m=\u001b[39;49maxis)\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\indexing.py:1497\u001b[0m, in \u001b[0;36m_iLocIndexer._getitem_axis\u001b[1;34m(self, key, axis)\u001b[0m\n\u001b[0;32m   1491\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mIndexError\u001b[39;00m(\n\u001b[0;32m   1492\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mDataFrame indexer is not allowed for .iloc\u001b[39m\u001b[39m\\n\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[0;32m   1493\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mConsider using .loc for automatic alignment.\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m   1494\u001b[0m     )\n\u001b[0;32m   1496\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(key, \u001b[39mslice\u001b[39m):\n\u001b[1;32m-> 1497\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_get_slice_axis(key, axis\u001b[39m=\u001b[39;49maxis)\n\u001b[0;32m   1499\u001b[0m \u001b[39mif\u001b[39;00m is_iterator(key):\n\u001b[0;32m   1500\u001b[0m     key \u001b[39m=\u001b[39m \u001b[39mlist\u001b[39m(key)\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\indexing.py:1532\u001b[0m, in \u001b[0;36m_iLocIndexer._get_slice_axis\u001b[1;34m(self, slice_obj, axis)\u001b[0m\n\u001b[0;32m   1529\u001b[0m     \u001b[39mreturn\u001b[39;00m obj\u001b[39m.\u001b[39mcopy(deep\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m)\n\u001b[0;32m   1531\u001b[0m labels \u001b[39m=\u001b[39m obj\u001b[39m.\u001b[39m_get_axis(axis)\n\u001b[1;32m-> 1532\u001b[0m labels\u001b[39m.\u001b[39;49m_validate_positional_slice(slice_obj)\n\u001b[0;32m   1533\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mobj\u001b[39m.\u001b[39m_slice(slice_obj, axis\u001b[39m=\u001b[39maxis)\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\indexes\\base.py:4006\u001b[0m, in \u001b[0;36mIndex._validate_positional_slice\u001b[1;34m(self, key)\u001b[0m\n\u001b[0;32m   4001\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   4002\u001b[0m \u001b[39mFor positional indexing, a slice must have either int or None\u001b[39;00m\n\u001b[0;32m   4003\u001b[0m \u001b[39mfor each of start, stop, and step.\u001b[39;00m\n\u001b[0;32m   4004\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m   4005\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_validate_indexer(\u001b[39m\"\u001b[39m\u001b[39mpositional\u001b[39m\u001b[39m\"\u001b[39m, key\u001b[39m.\u001b[39mstart, \u001b[39m\"\u001b[39m\u001b[39miloc\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m-> 4006\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_validate_indexer(\u001b[39m\"\u001b[39;49m\u001b[39mpositional\u001b[39;49m\u001b[39m\"\u001b[39;49m, key\u001b[39m.\u001b[39;49mstop, \u001b[39m\"\u001b[39;49m\u001b[39miloc\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[0;32m   4007\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_validate_indexer(\u001b[39m\"\u001b[39m\u001b[39mpositional\u001b[39m\u001b[39m\"\u001b[39m, key\u001b[39m.\u001b[39mstep, \u001b[39m\"\u001b[39m\u001b[39miloc\u001b[39m\u001b[39m\"\u001b[39m)\n",
            "File \u001b[1;32mc:\\Users\\jayso\\anaconda3\\envs\\PFT\\lib\\site-packages\\pandas\\core\\indexes\\base.py:6308\u001b[0m, in \u001b[0;36mIndex._validate_indexer\u001b[1;34m(self, form, key, kind)\u001b[0m\n\u001b[0;32m   6305\u001b[0m \u001b[39massert\u001b[39;00m kind \u001b[39min\u001b[39;00m [\u001b[39m\"\u001b[39m\u001b[39mgetitem\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39m\"\u001b[39m\u001b[39miloc\u001b[39m\u001b[39m\"\u001b[39m]\n\u001b[0;32m   6307\u001b[0m \u001b[39mif\u001b[39;00m key \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m is_integer(key):\n\u001b[1;32m-> 6308\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_invalid_indexer(form, key)\n",
            "\u001b[1;31mTypeError\u001b[0m: cannot do positional indexing on RangeIndex with these indexers [Bocas Fruit Co. Mov. De Contenedores Trasbordo] of type str"
          ]
        }
      ],
      "source": [
        "df.head(\"Bocas Fruit Co. Mov. De Contenedores Trasbordo\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "fig,ax=plt.subplots(figsize=(10,10))\n",
        "ax.set_title('Provincias de Panama',pad = 20)\n",
        "df.plot(column=\"name_1\",cmap = \"autumn_r\",ax=ax,zorder = 100)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Dash is running on http://127.0.0.1:5003/\n",
            "\n",
            " * Serving Flask app '__main__' (lazy loading)\n",
            " * Environment: production\n",
            "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
            "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
            " * Debug mode: off\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            " * Running on http://127.0.0.1:5003/ (Press CTRL+C to quit)\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET / HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_5_1m1657670236.12.1.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/deps/react@16.v2_5_1m1657670236.14.0.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_5_1m1657670236.8.1.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_5_1m1657670236.14.0.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_5_1m1657670236.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_5_0m1657670236.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_3m1657670236.min.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_5_0m1657670236.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_1_3m1657670236.js HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
            "127.0.0.1 - - [13/Jul/2022 12:12:20] \"GET /_favicon.ico?v=2.5.1 HTTP/1.1\" 200 -\n"
          ]
        }
      ],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "name": "Problema_4.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3.9.7 ('PFT')",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.7"
    },
    "vscode": {
      "interpreter": {
        "hash": "63b1c40a7ac4dbfdbb2ab7d022cd1f4b189732548a05b441943d353f5bc756d2"
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
